apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ladeit.fullname" . }}
  labels:
    app: {{ template "ladeit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "ladeit.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- if .Values.volume.enabled }}
          volumeMounts:
          - mountPath: {{ .Values.volume.mountPath }}
            name: {{ .Values.volume.name }}
          {{- end }}
          livenessProbe:
            failureThreshold: {{ .Values.probe.failureThreshold }}
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            successThreshold: {{ .Values.probe.successThreshold }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.probe.failureThreshold }}
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            successThreshold: {{ .Values.probe.successThreshold }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.persistentVolumeClaim.enabled }}
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.claimName }}
    {{- end }}
