# Default values for ladeit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ladeit/ladeit
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: ladeit
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000
ingress:
  enabled: true
  hosts:
    - ladeit-example.local
env:
  webkubectlhost: ladeit-example.com
resources:
  limits:
    cpu: 1500m
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 1Gi
volume:
  enabled: false
  mountPath: /root/.ladeit
  name: ladeit
persistentVolumeClaim:
  enabled: false
  claimName: ladeit
webkubectl:
  image:
    repository: kubeoperator/webkubectl
    tag: v2.4.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 500m
  service:
    name: webkubectl
    type: ClusterIP
    externalPort: 8080
    internalPort: 8080

